# Generated by Django 4.1.7 on 2023-04-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='authenticated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
