# Generated by Django 4.1.7 on 2023-04-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_contact_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
