# Generated by Django 4.1.6 on 2023-05-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='authenticated',
        ),
    ]
