# Generated by Django 4.2.1 on 2023-05-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0016_profile_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_To_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=10202020)),
                ('username', models.CharField(max_length=10202010)),
            ],
        ),
    ]
