# Generated by Django 4.2.1 on 2023-05-31 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_add_to_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_of_carts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
