# Generated by Django 4.2.1 on 2023-05-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0020_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='no_of_carts',
            field=models.IntegerField(default=0),
        ),
    ]
