# Generated by Django 4.2.1 on 2023-05-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_alter_product_no_of_carts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
