# Generated by Django 4.2.1 on 2023-05-31 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0022_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.CharField(default='Jordan', max_length=100000),
        ),
        migrations.AlterField(
            model_name='add_to_cart',
            name='cart_id',
            field=models.CharField(max_length=500000),
        ),
        migrations.AlterField(
            model_name='add_to_cart',
            name='username',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
