# Generated by Django 4.1.6 on 2023-06-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0023_product_user_alter_add_to_cart_cart_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_To_Cart',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
