# Generated by Django 4.1.6 on 2023-06-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0024_delete_add_to_cart_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adder', models.CharField(max_length=100000)),
                ('product', models.CharField(max_length=100000)),
            ],
        ),
    ]
