# Generated by Django 4.1.6 on 2023-06-29 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0025_cartscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_To_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_count', models.IntegerField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.profile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.product')),
            ],
        ),
        migrations.DeleteModel(
            name='CartsCount',
        ),
    ]
