# Generated by Django 4.1.6 on 2023-06-29 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0027_rename_add_to_cart_addtocart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.profile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.addtocart')),
            ],
        ),
    ]
